# -*- coding: utf-8 -*-
"""Image_hotsport.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FXBCTBifE1ZQw1eT-IJcSV4PnWos0vda
"""

!pip install -q ultralytics gradio opencv-python pillow

from ultralytics import YOLO
from PIL import Image
import gradio as gr
import numpy as np
import cv2

model = YOLO("yolov8n.pt")

stored_boxes = []
stored_image = None

def detect_objects(image):

    global stored_boxes
    global stored_image

    image_np = np.array(image)

    stored_image = image_np.copy()

    results = model(image_np)

    boxes = results[0].boxes
    names = results[0].names

    stored_boxes = []

    for box in boxes:

        cls_id = int(box.cls[0])
        label = names[cls_id]

        confidence = float(box.conf[0])

        x1, y1, x2, y2 = map(int, box.xyxy[0])

        stored_boxes.append({
            "label": label,
            "confidence": round(confidence, 2),
            "x1": x1,
            "y1": y1,
            "x2": x2,
            "y2": y2
        })

        cv2.rectangle(
            image_np,
            (x1, y1),
            (x2, y2),
            (0, 255, 0),
            2
        )

        cv2.putText(
            image_np,
            f"{label} {confidence:.2f}",
            (x1, y1 - 10),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (0, 255, 0),
            2
        )

    return Image.fromarray(image_np), stored_boxes

def hotspot_click(evt: gr.SelectData):

    x = evt.index[0]
    y = evt.index[1]

    for item in stored_boxes:

        if (
            item["x1"] <= x <= item["x2"] and
            item["y1"] <= y <= item["y2"]
        ):

            return f"""
Object Detected

Name: {item['label']}
Confidence: {item['confidence']}
Bounding Box:
x1={item['x1']}
y1={item['y1']}
x2={item['x2']}
y2={item['y2']}
"""

    return "No object detected"

with gr.Blocks() as demo:

    gr.Markdown("# AI Image Hotspot Detection")

    gr.Markdown(
        "Upload image → Detect objects → Click on object to identify it"
    )

    with gr.Row():

        with gr.Column():

            image_input = gr.Image(
                type="pil",
                label="Upload Image"
            )

            detect_btn = gr.Button("Detect Objects")

        with gr.Column():

            image_output = gr.Image(
                type="pil",
                label="Detected Objects"
            )

    result_box = gr.Textbox(
        label="Hotspot Detection Result",
        lines=10
    )

    json_output = gr.JSON(
        label="Detected Hotspots"
    )

    detect_btn.click(
        fn=detect_objects,
        inputs=image_input,
        outputs=[image_output, json_output]
    )

    image_output.select(
        fn=hotspot_click,
        outputs=result_box
    )

demo.launch(debug=True)

!pip install -q transformers torch torchvision pillow gradio timm

from transformers import OwlViTProcessor, OwlViTForObjectDetection
from PIL import Image, ImageDraw
import torch
import gradio as gr
import numpy as np

processor = OwlViTProcessor.from_pretrained("google/owlvit-base-patch32")
model = OwlViTForObjectDetection.from_pretrained("google/owlvit-base-patch32")

stored_boxes = []

labels = [
    "lamp",
    "chair",
    "table",
    "sofa",
    "bottle",
    "cup",
    "laptop",
    "phone",
    "book",
    "person",
    "tv",
    "plant",
    "fan",
    "bed",
    "clock"
]

def detect_objects(image):

    global stored_boxes

    stored_boxes = []

    image = image.convert("RGB")

    inputs = processor(
        text=[labels],
        images=image,
        return_tensors="pt"
    )

    with torch.no_grad():
        outputs = model(**inputs)

    target_sizes = torch.Tensor([image.size[::-1]])

    results = processor.post_process_object_detection(
        outputs=outputs,
        target_sizes=target_sizes,
        threshold=0.15
    )

    result = results[0]

    draw = ImageDraw.Draw(image)

    boxes = result["boxes"]
    scores = result["scores"]
    detected_labels = result["labels"]

    for box, score, label_idx in zip(boxes, scores, detected_labels):

        box = [round(i, 2) for i in box.tolist()]

        x1, y1, x2, y2 = map(int, box)

        label = labels[label_idx]

        stored_boxes.append({
            "label": label,
            "score": float(score),
            "x1": x1,
            "y1": y1,
            "x2": x2,
            "y2": y2
        })

        draw.rectangle(
            [(x1, y1), (x2, y2)],
            outline="red",
            width=3
        )

        draw.text(
            (x1, y1 - 15),
            f"{label} {score:.2f}",
            fill="red"
        )

    return image, stored_boxes

def hotspot_click(evt: gr.SelectData):

    x = evt.index[0]
    y = evt.index[1]

    for item in stored_boxes:

        if (
            item["x1"] <= x <= item["x2"] and
            item["y1"] <= y <= item["y2"]
        ):

            return f"""
Object Found

Name: {item['label']}
Confidence: {item['score']:.2f}

Coordinates:
({item['x1']}, {item['y1']})
({item['x2']}, {item['y2']})
"""

    return "No object detected"

with gr.Blocks() as demo:

    gr.Markdown("# Free AI Image Hotspot Detector")

    gr.Markdown(
        "Upload image → Detect objects → Click object to identify"
    )

    with gr.Row():

        with gr.Column():

            image_input = gr.Image(
                type="pil",
                label="Upload Image"
            )

            detect_btn = gr.Button("Detect Objects")

        with gr.Column():

            image_output = gr.Image(
                type="pil",
                label="Detected Objects"
            )

    result_box = gr.Textbox(
        label="Hotspot Result",
        lines=8
    )

    json_output = gr.JSON(
        label="Detected Objects JSON"
    )

    detect_btn.click(
        fn=detect_objects,
        inputs=image_input,
        outputs=[image_output, json_output]
    )

    image_output.select(
        fn=hotspot_click,
        outputs=result_box
    )

demo.launch(debug=True)